---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: hello-world
    environment: node
    part-of: demo
    tier: app
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: hello-world
    environment: node
    part-of: demo
    tier: app
