---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: hello-world
    environment: node
    part-of: demo
    tier: app
spec:
  selector:
    matchLabels:
      app: hello-world
      environment: node
      part-of: demo
      tier: app
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
        environment: node
        part-of: demo
        tier: app
    spec:
      containers:
        - name: demo
          image: demo:dev
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3000
